config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users

  root to: "home#index"
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    member do
      patch 'toggle'
    end
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :foods

  resources :recipes do
    member do
      get 'show_for_purpose1'
    end
  end
  
  get 'public_recipes', to: 'recipes#public_recipes', as: :public_recipes

  get 'general_list', to: 'general_list#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :destroy, Recipe, user_id: user.id

    can :destroy, Food, user_id: user.id
    can :update, Recipe, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  def calculate_total_amount
    total_amount = 0
    recipe_foods.each do |recipe_food|
      total_amount += recipe_food.food.price * recipe_food.quantity
    end
    total_amount
  end

  scope :public_recipes, -> { where(public: true) }

  def public?
    is_public
  end

  validates :name, presence: true, length: { in: 0..250 }
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :food, uniqueness: { scope: :recipe_id }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  accepts_nested_attributes_for :foods
  has_many :recipes, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show destroy]

  def index
    @foods = current_user.foods.includes(:user)
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food item added successfully.'
    else
      render :new
    end
  end

  def show
    @food = Food.find(params[:id])
    if @food.recipe_foods.empty?
      if @food.destroy
        redirect_to foods_path, notice: 'Food item deleted.'
      else
        redirect_to foods_path, alert: 'Failed to delete food item.'
      end
    else
      redirect_to foods_path, alert: 'Food item is still being used in recipes'
    end
  end

  private

  def set_food
    @food = current_user.foods.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/general_list_controller.rb
class GeneralListController < ApplicationController
  before_action :authenticate_user!

  def index
    @tot_price = 0
    @tot_count = 0
    @foods = Food.left_outer_joins(:recipe_foods).where(recipe_foods: { food_id: nil },
                                                        foods: { user_id: current_user.id })
    @foods.each do |t|
      @tot_price += t.price
      @tot_count += 1
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
    @title = 'Welcome to RecipeApp!'
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)

    if @recipe.user == current_user && @recipe_food.save
      flash[:success] = 'Ingredient successfully added'
      redirect_to @recipe
    else
      flash[:error] = 'Error adding ingredient'
      render :new
    end
  end

  def edit
    @recipe_food = @recipe.recipe_foods.find_by(id: params[:id])
  end

  def update
    @recipe_food = @recipe.recipe_foods.find(params[:id])

    if @recipe_food.update(recipe_food_params)
      flash[:notice] = 'The ingredient was modified successfully!'
      redirect_to @recipe # Redirect to the show page for the updated food
    else
      flash[:alert] = @recipe_food.errors.full_messages.join(', ')
      render :edit # Render the edit page again with error messages
    end
  end

  def destroy
    @recipe_food = @recipe.recipe_foods.find(params[:id])

    if @recipe_food.destroy
      redirect_to @recipe, notice: 'Recipe food was successfully destroyed.'
    else
      flash[:alert] = 'Failed to destroy recipe food.'
      render :show
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end

  def set_recipe
    @foods = current_user.foods.all
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @recipe_food = @recipe.recipe_foods
    # Select the foods that are not in the recipe.
    @foods_not_in_recipe = @foods.where.not(id: @recipe_food.pluck(:food_id))
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :authorize_recipe_toggle, only: [:toggle]

  def index
    @user_recipes = Recipe.where(user_id: current_user.id)
    @user = current_user.recipes.includes(:user)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe added successfully.'
    else
      render :new
    end
  end

  def show_for_purpose1
    @recipe = Recipe.find(params[:id])
    authorize! :destroy, @recipe
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was deleted successfully.'
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.update(is_public: !@recipe.is_public)

    if @recipe.is_public?
      session[:public_recipes] ||= []
      session[:public_recipes] << @recipe.id
    elsif session[:public_recipes]
      session[:public_recipes].delete(@recipe.id)
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
    end
  end

  def public_recipes
    @public_recipes = Recipe.where(is_public: true).order(created_at: :desc)
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe deleted successfully.'
  end

  private

  def authorize_recipe_toggle
    @recipe = Recipe.find(params[:id])
    return if @recipe.user_id == current_user.id

    flash[:error] = 'You are not authorized to perform this action.'
    redirect_to recipes_path
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_list_helper.rb
module GeneralListHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<div class=container-f>
<h1>Your Food List</h1>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Measurement Unit</th>
    <th>Unit Price</th>
    <th>Action</th>
  </tr>
  <% @foods.each do |food| %>
    <tr>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td><%= number_to_currency(food.price, unit: "$") %></td>
      <td><%= link_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<div class="mov">
<button class="button">
<%= link_to 'Add Food', new_food_path %>
</button>
<div>

</div>

app/views/foods/new.html.erb
<h1>Add New Food Item</h1>

<%= form_for @food do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :measurement_unit %>
    <%= f.text_field :measurement_unit %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit 'Add Food' %>
  </div>
<% end %>

<%= link_to 'Back to Food List', foods_path %>

app/views/general_list/index.html.erb
<div class=container-f>
<h1 class="title-franck"> Shopping List </h1>
<br>
<div class="total">
<h3>Total value of food needed : <%= @tot_price %></h3>
<h3>Amount of food items to buy : <%= @tot_count %></h3>
</div>
<% if @foods.empty? %>
<h1> Every foods is connected to recipe </h1>
<% else %>
<table id="customers">
<tr>
<th>Foods</th><th>Quantity</th><th>Price</th>
</tr>
<% @foods.each do |f| %>
    <tr>
      <td><%= f.name %></td><td><%= f.quantity %></td><td><%= f.price %></td>
    </tr>
<% end %>
</table>
<% end %>
</div>

app/views/home/index.html.erb
<div class="home-content">
  <h1 class="home"><%= @title %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>  
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Food List", foods_path %></li>
      <li><%= link_to "Recipe List", recipes_path %></li>
      <li><%= link_to 'Public Recipes', public_recipes_path %></li>
      <li><%= link_to "General List", general_list_path %></li>
    </ul>

    <!-- Add flash messages for success and error -->
    <div class="flash-notice">
      <%= notice %>
    </div>
    <div class="flash-alert">
      <%= alert %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Navigation Bar or links to other pages -->
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Food List", foods_path %></li>
        <li><%= link_to "Recipe List", recipes_path %></li>
        <li><%= link_to 'Public Recipes', public_recipes_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
      </ul>
    </nav>

    <!-- Home Page Content -->
    <div class="home-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_form.html.erb
<%= form_with(model: [@recipe, @recipe_food], url: recipe_recipe_foods_path(@recipe), local: true) do |form| %>
  <% if @recipe_food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>
      <ul>
        <!-- Error messages handling -->
        <% @recipe_food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Form fields -->
  <%= form.label :food_id, "Food" %>
  <%= form.collection_select :food_id, Food.all, :id, :name %>
  <%= form.label :quantity, "Quantity" %>
  <%= form.number_field :quantity %>

  <!-- Submit button -->
  <%= form.submit 'Create Recipe Food' %>
<% end %>

app/views/recipe_foods/edit.html.erb
<h1>Edit an ingredient</h1>

<%= form_with(model: [@recipe, @recipe_food], url: recipe_recipe_food_path(@recipe, @recipe_food), method: :patch) do |form| %>
  <% if @recipe_food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>
      <ul>
        <!-- Error messages handling -->
        <% @recipe_food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Form fields -->
  <%= form.label :food_id, "Food" %>
  <%= form.collection_select :food_id, [@recipe_food.food], :id, :name %>
  <%= form.label :quantity, "Quantity" %>
  <%= form.number_field :quantity %>

  <!-- Submit button -->
  <%= form.submit 'Save ingredient' %>
  <%= link_to 'Back', recipe_path(@recipe, @recipe_food), class: 'btn btn-secondary' %>
<% end %>

app/views/recipe_foods/new.html.erb
<h2>Add New Ingredient</h2>

<%= form_with(model: [@recipe, @recipe_food], local: true) do |form| %>
  <div class="field">
    <%= form.label :food_id, 'Food' %>
    <%= form.collection_select :food_id, @foods, :id, :name, prompt: 'Select food item' %>
  </div>

  <div class="field">
    <%= form.label :quantity, 'Quantity' %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit 'Add Ingredient' %>
    <%= link_to 'Cancel', recipe_path(@recipe), class: 'button' %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<% if @user_recipes.empty? %>
  <p> You have not created recipes yet </p>
<% else %>
	<% @user_recipes.each do |recipe| %>
			<div class="recipe">
				<div class="recipe_links">
					<h2><%= link_to recipe.name, recipe_path(recipe, recipe) %></h2>
					<% if can? :destroy, recipe %>
                      <%= link_to 'Delete', show_for_purpose1_recipe_path(recipe) %>
					<% end %>
				</div>
				<div>
					<p><%= recipe.description %></p>
				</div>
			</div>
	<% end %>
<% end %>
<div class="mov">
<button class="button">
<%= link_to 'Create Recipe', new_recipe_path %>
</button>
<div>

app/views/recipes/new.html.erb
<h1>Add New Recipe</h1>

<%= form_for @recipe do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :preparation_time %>
    <%= f.number_field :preparation_time %>
  </div>

  <div class="field">
    <%= f.label :cooking_time %>
    <%= f.number_field :cooking_time %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit 'Add Recipe' %>
  </div>
<% end %>

<%= link_to 'Back to Recipe List', recipes_path %>

app/views/recipes/public_recipes.html.erb
<h1>Public Recipes</h1>

<% @public_recipes.each do |recipe| %>
  <div class="public_recipe_list">
    <div>
      <h3><%= link_to recipe.name, recipe_path(recipe, recipe) %></h3>
      <p>By: <%= recipe.user.name %></p>
    </div>
    <div>
      <p>Total Food Items: <%= recipe.recipe_foods.count %></p>
      <p class="public_recipe_amount">Total Price: $<%= recipe.calculate_total_amount %></p>
    </div>
  </div>
  <hr>
<% end %>

app/views/recipes/show.html.erb
<main class="recipe_food_container">
  <h3 class="recipe-name"><%= @recipe.name %></h3>

  <section id="recipe_food_details">
    <div class="description-container">
      <div class="recipe_detail_container">
        <p> Preparation Time: <%= @recipe.preparation_time %> hour </p>
        <p> Cooking Time: <%= @recipe.cooking_time %> hour </p>
        <p> <%= @recipe.description %> </p>
      </div>
    </div>
    <div class="toggle-container">
      <% if @recipe.user_id == current_user.id %>
        <%= form_with model: @recipe, url: toggle_recipe_path(@recipe), method: :patch, local: true do |form| %>
          <% new_public_status = !@recipe.is_public %>
          <span class="status-text"><%= new_public_status ? 'Private' : 'Public' %></span>
          <label class="switch">
            <input type="hidden" name="recipe[public]" value="0"> <!-- Hidden field for false value -->
            <div class="toggle_status_container">
              <button type="submit" class="toggle-button <%= @recipe.is_public ? 'private' : 'public' %>"></button>
            </div>
          </label>
          <%= form.hidden_field :public, value: new_public_status %>
        <% end %>
     <% end %>
    </div>
  </section>
  <section>

  <%= link_to 'Generate Shopping List', general_list_path %>

   

    <% if @recipe.user == current_user %>
      <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe) %>
    <% end %>
  </section>
  <section>
    <table id="recipe_food_table" class="table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |recipe_food| %>
          <% food = recipe_food.food %>
          <tr>
            <td><%= food.name %></td>
            <td><%= recipe_food.quantity %> <%= food.measurement_unit %></td>
            <td> $<%= food.price * recipe_food.quantity %></td>
            <td>
              <% if @recipe.user == current_user %>
                <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food) %>
              <% end %> 
              <% if @recipe.user == current_user %>
                <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' } %>
              <% end %>  
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
</main>